create table public.ai_kitchen_generation_requests (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users (id) on delete cascade,
  request_id text not null check (char_length(request_id) between 8 and 128),
  idempotency_key text not null check (char_length(idempotency_key) between 16 and 128),
  request_hash text not null check (request_hash ~ '^[0-9a-f]{64}$'),
  schema_version text not null,
  client_version text not null,
  locale text not null default 'zh-CN' check (locale in ('zh-CN', 'en-US')),
  request_payload jsonb not null,
  status text not null check (status in ('processing', 'succeeded', 'no_match', 'failed', 'timeout', 'service_unavailable', 'rate_limited')),
  response_payload jsonb,
  error_code text,
  provider_request_id text,
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  completed_at timestamptz,
  unique (owner_id, request_id),
  unique (owner_id, idempotency_key)
);

create index ai_kitchen_generation_owner_created_idx on public.ai_kitchen_generation_requests (owner_id, created_at desc);
create index ai_kitchen_generation_status_updated_idx on public.ai_kitchen_generation_requests (status, updated_at desc);

create table public.ai_kitchen_recipes (
  recipe_id uuid primary key,
  owner_id uuid not null references auth.users (id) on delete cascade,
  schema_version text not null,
  source text not null check (source in ('local', 'deterministic', 'provider')),
  provider text,
  model text,
  title text not null,
  locale text not null default 'zh-CN' check (locale in ('zh-CN', 'en-US')),
  cooking_method text check (cooking_method is null or cooking_method in ('stir-fry', 'stew', 'steam', 'soup', 'cold', 'roast')),
  cuisine text check (cuisine is null or cuisine in ('sichuan', 'cantonese', 'hunan', 'jiangsu', 'zhejiang', 'northeastern', 'shandong', 'western', 'japanese', 'korean', 'other')),
  flavor text check (flavor is null or flavor in ('light', 'spicy', 'savory', 'sweet', 'sour', 'sweet-sour', 'salty')),
  recipe_payload jsonb not null,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  unique (owner_id, recipe_id)
);

create index ai_kitchen_recipe_owner_locale_idx on public.ai_kitchen_recipes (owner_id, locale, created_at desc);

create table public.ai_kitchen_recipe_history (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users (id) on delete cascade,
  recipe_id uuid not null,
  source text not null check (source in ('local', 'remote')),
  first_visited_at timestamptz not null default clock_timestamp(),
  last_visited_at timestamptz not null default clock_timestamp(),
  visit_count integer not null default 1 check (visit_count > 0),
  unique (owner_id, recipe_id),
  foreign key (owner_id, recipe_id) references public.ai_kitchen_recipes (owner_id, recipe_id) on delete cascade
);

create index ai_kitchen_history_owner_last_visited_idx on public.ai_kitchen_recipe_history (owner_id, last_visited_at desc, recipe_id desc);

create table public.ai_kitchen_rate_limits (
  owner_id uuid primary key references auth.users (id) on delete cascade,
  window_started_at timestamptz not null,
  request_count integer not null check (request_count > 0),
  updated_at timestamptz not null default clock_timestamp()
);

alter table public.ai_kitchen_generation_requests enable row level security;
alter table public.ai_kitchen_recipes enable row level security;
alter table public.ai_kitchen_recipe_history enable row level security;
alter table public.ai_kitchen_rate_limits enable row level security;

create policy ai_kitchen_generation_owner_all
  on public.ai_kitchen_generation_requests for all to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

create policy ai_kitchen_recipe_owner_all
  on public.ai_kitchen_recipes for all to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

create policy ai_kitchen_history_owner_all
  on public.ai_kitchen_recipe_history for all to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

create policy ai_kitchen_rate_limit_owner_all
  on public.ai_kitchen_rate_limits for all to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

revoke all on table public.ai_kitchen_generation_requests from anon, authenticated;
revoke all on table public.ai_kitchen_recipes from anon, authenticated;
revoke all on table public.ai_kitchen_recipe_history from anon, authenticated;
revoke all on table public.ai_kitchen_rate_limits from anon, authenticated;
grant select, insert, update, delete on table public.ai_kitchen_generation_requests to authenticated;
grant select, insert, update, delete on table public.ai_kitchen_recipes to authenticated;
grant select, insert, update, delete on table public.ai_kitchen_recipe_history to authenticated;
grant select, insert, update, delete on table public.ai_kitchen_rate_limits to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.ai_kitchen_reserve_generation(
  p_request_id text,
  p_idempotency_key text,
  p_request_hash text,
  p_schema_version text,
  p_client_version text,
  p_locale text,
  p_request_payload jsonb
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_owner uuid := auth.uid();
  v_row public.ai_kitchen_generation_requests%rowtype;
begin
  if v_owner is null then raise exception 'authentication required'; end if;

  select * into v_row
  from public.ai_kitchen_generation_requests
  where owner_id = v_owner and idempotency_key = p_idempotency_key
  for update;
  if not found then
    select * into v_row
    from public.ai_kitchen_generation_requests
    where owner_id = v_owner and request_id = p_request_id
    for update;
  end if;

  if found then
    if v_row.request_hash <> p_request_hash then return jsonb_build_object('kind', 'conflict'); end if;
    if v_row.status = 'processing' then return jsonb_build_object('kind', 'in_progress'); end if;
    if v_row.response_payload is not null then return jsonb_build_object('kind', 'replay', 'response', v_row.response_payload); end if;
    return jsonb_build_object('kind', 'conflict');
  end if;

  begin
    insert into public.ai_kitchen_generation_requests (
      owner_id, request_id, idempotency_key, request_hash, schema_version,
      client_version, locale, request_payload, status
    ) values (
      v_owner, p_request_id, p_idempotency_key, p_request_hash, p_schema_version,
      p_client_version, p_locale, p_request_payload, 'processing'
    );
  exception when unique_violation then
    select * into v_row
    from public.ai_kitchen_generation_requests
    where owner_id = v_owner and (idempotency_key = p_idempotency_key or request_id = p_request_id)
    order by case when idempotency_key = p_idempotency_key then 0 else 1 end
    limit 1
    for update;
    if v_row.request_hash <> p_request_hash then return jsonb_build_object('kind', 'conflict'); end if;
    if v_row.status = 'processing' then return jsonb_build_object('kind', 'in_progress'); end if;
    if v_row.response_payload is not null then return jsonb_build_object('kind', 'replay', 'response', v_row.response_payload); end if;
    return jsonb_build_object('kind', 'conflict');
  end;
  return jsonb_build_object('kind', 'new');
end;
$$;

create or replace function public.ai_kitchen_complete_generation(
  p_idempotency_key text,
  p_request_hash text,
  p_status text,
  p_response jsonb,
  p_duration_ms integer
) returns void
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if p_status not in ('succeeded', 'no_match') then raise exception 'invalid completion status'; end if;
  update public.ai_kitchen_generation_requests
  set status = p_status, response_payload = p_response, duration_ms = p_duration_ms,
      completed_at = clock_timestamp(), updated_at = clock_timestamp(), error_code = null
  where owner_id = auth.uid() and idempotency_key = p_idempotency_key and request_hash = p_request_hash;
  if not found then raise exception 'generation reservation not found'; end if;
end;
$$;

create or replace function public.ai_kitchen_fail_generation(
  p_idempotency_key text,
  p_request_hash text,
  p_status text,
  p_error_code text,
  p_duration_ms integer
) returns void
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if p_status not in ('failed', 'timeout', 'service_unavailable', 'rate_limited') then raise exception 'invalid failure status'; end if;
  update public.ai_kitchen_generation_requests
  set status = p_status, error_code = p_error_code, duration_ms = p_duration_ms,
      completed_at = clock_timestamp(), updated_at = clock_timestamp()
  where owner_id = auth.uid() and idempotency_key = p_idempotency_key and request_hash = p_request_hash;
  if not found then raise exception 'generation reservation not found'; end if;
end;
$$;

create or replace function public.ai_kitchen_save_recipe_success(
  p_idempotency_key text,
  p_request_hash text,
  p_response jsonb,
  p_recipes jsonb,
  p_duration_ms integer
) returns void
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_owner uuid := auth.uid();
  v_recipe jsonb;
  v_recipe_id uuid;
  v_metadata jsonb := p_response -> 'metadata';
begin
  if v_owner is null then raise exception 'authentication required'; end if;
  if jsonb_typeof(p_recipes) <> 'array' or jsonb_array_length(p_recipes) = 0 then raise exception 'recipes must be a non-empty array'; end if;

  for v_recipe in select value from jsonb_array_elements(p_recipes)
  loop
    v_recipe_id := (v_recipe ->> 'recipeId')::uuid;
    insert into public.ai_kitchen_recipes (
      recipe_id, owner_id, schema_version, source, provider, model, title, locale,
      cooking_method, cuisine, flavor, recipe_payload
    ) values (
      v_recipe_id,
      v_owner,
      v_metadata ->> 'recipeSchemaVersion',
      v_metadata ->> 'source',
      v_metadata ->> 'provider',
      v_metadata ->> 'model',
      v_recipe ->> 'title',
      v_recipe ->> 'locale',
      v_recipe ->> 'cookingMethod',
      v_recipe ->> 'cuisine',
      v_recipe ->> 'flavor',
      v_recipe
    )
    on conflict (recipe_id) do update set
      schema_version = excluded.schema_version,
      source = excluded.source,
      provider = excluded.provider,
      model = excluded.model,
      title = excluded.title,
      locale = excluded.locale,
      cooking_method = excluded.cooking_method,
      cuisine = excluded.cuisine,
      flavor = excluded.flavor,
      recipe_payload = excluded.recipe_payload,
      updated_at = clock_timestamp()
    where public.ai_kitchen_recipes.owner_id = v_owner;

    insert into public.ai_kitchen_recipe_history (owner_id, recipe_id, source)
    values (v_owner, v_recipe_id, 'remote')
    on conflict (owner_id, recipe_id) do update set
      source = excluded.source,
      last_visited_at = clock_timestamp(),
      visit_count = public.ai_kitchen_recipe_history.visit_count + 1;
  end loop;

  update public.ai_kitchen_generation_requests
  set status = 'succeeded', response_payload = p_response, duration_ms = p_duration_ms,
      completed_at = clock_timestamp(), updated_at = clock_timestamp(), error_code = null
  where owner_id = v_owner and idempotency_key = p_idempotency_key and request_hash = p_request_hash;
  if not found then raise exception 'generation reservation not found'; end if;
end;
$$;

create or replace function public.ai_kitchen_visit_history(p_recipe_id uuid, p_source text)
returns boolean
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if p_source not in ('local', 'remote') then raise exception 'invalid history source'; end if;
  update public.ai_kitchen_recipe_history
  set source = p_source, last_visited_at = clock_timestamp(), visit_count = visit_count + 1
  where owner_id = auth.uid() and recipe_id = p_recipe_id;
  return found;
end;
$$;

create or replace function public.ai_kitchen_get_recipe(p_recipe_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select recipe_payload
  from public.ai_kitchen_recipes
  where owner_id = auth.uid() and recipe_id = p_recipe_id
  limit 1
$$;

create or replace function public.ai_kitchen_list_history(
  p_locale text,
  p_limit integer,
  p_cursor_time timestamptz default null,
  p_cursor_recipe_id uuid default null
) returns table (
  recipe_id uuid,
  recipe_payload jsonb,
  source text,
  first_visited_at timestamptz,
  last_visited_at timestamptz,
  visit_count integer
)
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select h.recipe_id, r.recipe_payload, h.source, h.first_visited_at, h.last_visited_at, h.visit_count
  from public.ai_kitchen_recipe_history h
  join public.ai_kitchen_recipes r on r.owner_id = h.owner_id and r.recipe_id = h.recipe_id
  where h.owner_id = auth.uid()
    and r.locale = p_locale
    and (
      p_cursor_time is null
      or h.last_visited_at < p_cursor_time
      or (h.last_visited_at = p_cursor_time and h.recipe_id < p_cursor_recipe_id)
    )
  order by h.last_visited_at desc, h.recipe_id desc
  limit least(greatest(p_limit, 1), 51)
$$;

create or replace function public.ai_kitchen_allow_request(p_limit integer default 10, p_window_seconds integer default 60)
returns boolean
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_owner uuid := auth.uid();
  v_row public.ai_kitchen_rate_limits%rowtype;
  v_now timestamptz := clock_timestamp();
begin
  if v_owner is null then raise exception 'authentication required'; end if;
  if p_limit < 1 or p_window_seconds < 1 then raise exception 'invalid rate limit'; end if;
  select * into v_row from public.ai_kitchen_rate_limits where owner_id = v_owner for update;
  if not found then
    insert into public.ai_kitchen_rate_limits (owner_id, window_started_at, request_count) values (v_owner, v_now, 1);
    return true;
  end if;
  if v_row.window_started_at + make_interval(secs => p_window_seconds) <= v_now then
    update public.ai_kitchen_rate_limits set window_started_at = v_now, request_count = 1, updated_at = v_now where owner_id = v_owner;
    return true;
  end if;
  if v_row.request_count >= p_limit then return false; end if;
  update public.ai_kitchen_rate_limits set request_count = request_count + 1, updated_at = v_now where owner_id = v_owner;
  return true;
end;
$$;

revoke all on function public.ai_kitchen_reserve_generation(text, text, text, text, text, text, jsonb) from public, anon;
revoke all on function public.ai_kitchen_complete_generation(text, text, text, jsonb, integer) from public, anon;
revoke all on function public.ai_kitchen_fail_generation(text, text, text, text, integer) from public, anon;
revoke all on function public.ai_kitchen_save_recipe_success(text, text, jsonb, jsonb, integer) from public, anon;
revoke all on function public.ai_kitchen_visit_history(uuid, text) from public, anon;
revoke all on function public.ai_kitchen_get_recipe(uuid) from public, anon;
revoke all on function public.ai_kitchen_list_history(text, integer, timestamptz, uuid) from public, anon;
revoke all on function public.ai_kitchen_allow_request(integer, integer) from public, anon;

grant execute on function public.ai_kitchen_reserve_generation(text, text, text, text, text, text, jsonb) to authenticated;
grant execute on function public.ai_kitchen_complete_generation(text, text, text, jsonb, integer) to authenticated;
grant execute on function public.ai_kitchen_fail_generation(text, text, text, text, integer) to authenticated;
grant execute on function public.ai_kitchen_save_recipe_success(text, text, jsonb, jsonb, integer) to authenticated;
grant execute on function public.ai_kitchen_visit_history(uuid, text) to authenticated;
grant execute on function public.ai_kitchen_get_recipe(uuid) to authenticated;
grant execute on function public.ai_kitchen_list_history(text, integer, timestamptz, uuid) to authenticated;
grant execute on function public.ai_kitchen_allow_request(integer, integer) to authenticated;
